# Create Class and Object:

In [6]:
class Mobile:
    def make_call(self):
        print("I am here to provide call_service to you")
    def play_game(self):
        print("I am here to provide a platform for playing games ")

In [7]:
m1 = Mobile()

In [8]:
m1.make_call()

I am here to provide call_service to you


In [9]:
m1.play_game()

I am here to provide a platform for playing games 


# Adding parameters to the class:

In [1]:
class Mobile:
    def set_color(self,color):
        self.color = color
    def set_cost(self,cost):
        self.cost = cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost
    def make_call(self):
        print("make a call")
    def play_game(self):
        print("play a game")

In [2]:
m = Mobile()

In [28]:
m.set_color('black')
m.set_cost(10000)

In [30]:
m.show_color()

'black'

In [7]:
m.show_cost()

10000

In [8]:
m.make_call()

make a call


In [9]:
m.play_game()

play a game


# Create a class with constructor:

In [10]:
class Employee:
    def __init__(self,name,age,salary,gender):
        self.name = name
        self.age = age
        self.salary = salary
        self.gender = gender
    def show_employee_details(self):
        print("Name of employee is ",self.name)
        print("Age of employee is ",self.age)
        print("Salary of employee is ",self.salary)
        print("Gender of employee is ",self.gender)

In [14]:
e1 = Employee('Khizar',20,50000,'Male')

In [15]:
e2 = Employee('Aiman',18,80000,'Female')

In [16]:
e1.show_employee_details()

Name of employee is  Khizar
Age of employee is  20
Salary of employee is  50000
Gender of employee is  Male


In [17]:
e2.show_employee_details()

Name of employee is  Aiman
Age of employee is  18
Salary of employee is  80000
Gender of employee is  Female


# Inheritance:

In [18]:
class Vehicle:
    def __init__(self,name,color,cost):
        self.name = name
        self.color = color
        self.cost = cost
    def show_vehicle_details(self):
        print("I am Vehicle")
        print("Name of vehicle is ",self.name)
        print("Color of vehicle is ",self.color)
        print("Cost of vehicle is ",self.cost)

In [21]:
v = Vehicle('Bus','Blue','5000$')

In [22]:
v.show_vehicle_details()

I am Vehicle
Name of vehicle is  Bus
Color of vehicle is  Blue
Cost of vehicle is  5000$


In [23]:
class Car(Vehicle):
    def show_car_details(self):
        print("I am Car")

In [25]:
c = Car('Mercedes','Black','8000$')

In [26]:
c.show_car_details()

I am Car


In [27]:
c.show_vehicle_details()

I am Vehicle
Name of vehicle is  Mercedes
Color of vehicle is  Black
Cost of vehicle is  8000$


# Over_riding of method:

In [31]:
class Vehicle:
    def __init__(self,name,color,cost):
        self.name = name
        self.color = color
        self.cost = cost
    def show_vehicle_details(self):
        print("I am Vehicle")
        print("Name of vehicle is ",self.name)
        print("Color of vehicle is ",self.color)
        print("Cost of vehicle is ",self.cost)

In [32]:
v = Vehicle('Bus','White','6000$')

In [43]:
class Car(Vehicle):
    def __init__(self,name,color,cost,tyre,hp):
        super().__init__(name,color,cost)
        self.tyre = tyre
        self.hp = hp
    def show_vehicle_details(self):     # overriding the method
        super().show_vehicle_details()    # call the parent class method
        print("Number of tyres are ",self.tyre)
        print("Number of horse powers are ",self.hp)
        

In [44]:
c1 = Car('Toyota','Black','7000$',4,250)

In [45]:
c1.show_vehicle_details()

I am Vehicle
Name of vehicle is  Toyota
Color of vehicle is  Black
Cost of vehicle is  7000$
Number of tyres are  4
Number of horse powers are  250


If you write "show_car_details" method in child class then it is not override.It will be a new method.Because overriding means "name of method is same that is used in parent class".

# Multiple inheritance: 

In [11]:
class Parent1:
    def assign_string1(self,str1):
        self.str1 = str1
    def show_string1(self):
        return self.str1

In [12]:
class Parent2:
    def assign_string2(self,str2):
        self.str2 = str2
    def show_string2(self):
        return self.str2

In [13]:
class Child(Parent1,Parent2):
    def assign_string3(self,str3):
        self.str3 = str3
    def show_string3(self):
        return self.str3
    

In [14]:
my_child = Child() 

In [15]:
my_child.assign_string1("I am string of parent 1")

In [16]:
my_child.assign_string2("I am string of parent 2")

In [17]:
my_child.assign_string3("I am string of child")

In [19]:
my_child.show_string1()

'I am string of parent 1'

In [20]:
my_child.show_string2()

'I am string of parent 2'

In [21]:
my_child.show_string3()

'I am string of child'

# Multi level inheritance: 

In [60]:
class Parent:
    def set_name(self,n):
        self.name = n
    def show_name(self):
        return self.name

In [61]:
class Child(Parent):
    def set_age(self,a):
        self.age = a
    def show_age(self):
        return self.age

In [62]:
class GrandChild(Child):
    def set_gender(self,g):
        self.g = g
    def show_gender(self):
        return self.g

In [63]:
gc = GrandChild()

In [64]:
gc.set_name('Khizar')

In [65]:
gc.set_age(20)

In [66]:
gc.set_gender('Male')

In [67]:
gc.show_name()

'Khizar'

In [68]:
gc.show_age()

20

In [69]:
gc.show_gender()

'Male'

The OOP session has ended 25/07/2025 at 11:39 pm. 
Alhamdullilah................

In [1]:
import numpy as np

In [2]:
list = [1,2,3,4,5]

In [3]:
n1 = np.array(list)

In [4]:
n1

array([1, 2, 3, 4, 5])

In [6]:
type(n1)

numpy.ndarray

In [8]:
l1 = [2,4,5]

In [9]:
l2 = [7,3,6]

In [11]:
n2 = np.array([l1,l2])

In [12]:
n2

array([[2, 4, 5],
       [7, 3, 6]])

In [13]:
type(n2)

numpy.ndarray

In [15]:
n3 = np.zeros((2,3))

In [16]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
n4 = np.full((3,3),5)

In [20]:
n4

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [21]:
n5 = np.arange(1,30)

In [22]:
n5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
n6 = np.arange(100,500,10)

In [24]:
n6

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220,
       230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350,
       360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480,
       490])

In [33]:
n7 = np.random.randint(50,150,10)

In [34]:
n7

array([ 66,  87, 101,  74, 140, 108, 144,  89, 133, 123])

In [41]:
n8 = np.array([[1,4,5,6],[3,5,6,7]])

In [42]:
n8

array([[1, 4, 5, 6],
       [3, 5, 6, 7]])

In [43]:
n8.shape

(2, 4)

In [44]:
n8.shape = (4,2)       #shape change

In [45]:
n8

array([[1, 4],
       [5, 6],
       [3, 5],
       [6, 7]])

In [ ]:
# for joining numpy arrays

In [46]:
n9 = np.array([2,4,6])

In [47]:
n10 = np.array([3,6,8])

In [49]:
np.vstack((n9,n10))

array([[2, 4, 6],
       [3, 6, 8]])

In [50]:
np.hstack((n9,n10))

array([2, 4, 6, 3, 6, 8])

In [52]:
np.column_stack((n9,n10))

array([[2, 3],
       [4, 6],
       [6, 8]])

In [ ]:
# for intersection and difference operations

In [53]:
n11 = np.array([50,34,45,23,47])

In [54]:
n12 = np.array([23,45,78,90,50])

In [55]:
np.intersect1d(n11,n12)

array([23, 45, 50])

In [57]:
np.setdiff1d(n11,n12)

array([34, 47])

In [58]:
np.setdiff1d(n12,n11)

array([78, 90])

In [ ]:
# for purpose of adding values in array/matrix

In [2]:
n13 = np.array([20, 40])
n14 = np.array([45, 25])

result = np.sum([n13, n14])
print(result)


130


In [3]:
np.sum([n13,n14],axis = 0)

array([65, 65])

In [4]:
np.sum([n13,n14],axis = 1)

array([60, 70])